---
abstract: 'First attempt at writing a modern Plugwise Perl module'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Plugwise
requires:
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/hollie/device-plugwise-perl.git
version: 1.122570
