---
abstract: 'Perl module to communicate with Plugwise hardware'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Plugwise
requires:
  Carp: 0
  Data::Dumper: 0
  Device::SerialPort: 0
  Digest::CRC: 0
  Fcntl: 0
  IO::File: 0
  IO::Select: 0
  IO::Socket::INET: 0
  Math::Round: 0
  Socket: 0
  Symbol: 0
  Time::HiRes: 0
  constant: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/hollie/device-plugwise-perl/issues
  repository: git://github.com/hollie/device-plugwise-perl.git
version: 0.5
